# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-24 11:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='todo_comment',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
